### ISSUE TITLE
ImportError: (test_gtk2player.py and test_gtk3player.py )

### ISSUE THREAD

**Issue by iharsh234** [P2PSP/core#103]
Previously the GUI folder was not there and after moving modules to GUI directory the import statements not changed which causing Import Error. 
Fixed  test_gtk3player.py    2e0da519f2227f99d29f19ec9ef9ac2edd9a4cfd
Fixed  test_gtk2player.py     05565acf18d5c1ee0e6df014eff097703eeb1dcf

**Comment by cristobalmedinalopez** [comment]
Yes, you are right. However we'll move the GUI part to another different repository. We'll apply changes there.

Thanks!

**Comment by vicente-gonzalez-ruiz** [comment]
The GUI stuff should be discussed in a different repository.
