### ISSUE TITLE
Enable parallel compilation

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [P2PSP/core#108]
I don't know how to achieve this, but it would be a nice feature :-)

**Comment by jellysheep** [comment]
Hi Vicente, this is easily accomplished by calling make with e.g. the parameter '-j4' (for 4 files compiled in parallel, if this is what you mean), but on Unix-like 'make' only. This can't be configured in CMake though, but it could be put into make.py.

**Comment by vicente-gonzalez-ruiz** [comment]
Thanks @jellysheep!

**Comment by vicente-gonzalez-ruiz** [comment]
Done
