### ISSUE TITLE
Automatic selection of Set of Rules by magic flags from splitter

### ISSUE THREAD

**Issue by jellysheep** [P2PSP/core#111]
A peer should be able to automatically select the needed peer class (Set of Rules) based on the magic flags sent by the splitter.
The following method is proposed:
- An initial/startup peer class ("InitPeer", or just "Peer", or "Player"?) handles the connection to splitter, and loading configuration, header and list of peers from splitter.
- The startup peer class creates an instance of the needed peer class derived from PeerIMS, in a similar way like [the splitter currently is implemented](https://github.com/P2PSP/p2psp-console/blob/05a8056e5df1401c44fad648bb87d23d288ff607/src/splitter.cc#L184). This instance is provided by the (Init)Peer class to get access to its methods.

A possible implementation proposal will follow. Any comments or suggestions are highly appreciated.

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @jellysheep, so do you propose to use (in the peer.cc of the p2psp-console repo) some similar to:
```
if (vm.count("strpe")) {
    //splitter_ptr.reset(new p2psp::SplitterSTRPE());
  } else if (vm.count("NTS")) {
    splitter_ptr.reset(new p2psp::SplitterNTS());
  } else if (vm.count("LRS")) {
    splitter_ptr.reset(new p2psp::SplitterLRS());
  } else if (vm.count("ACS")) {
    splitter_ptr.reset(new p2psp::SplitterACS());
  } else if (vm.count("IMS")) {
    is_IMS_only = true;
    splitter_ptr.reset(new p2psp::SplitterIMS());
  } else {
    splitter_ptr.reset(new p2psp::SplitterDBS());
  }
```
but deciding with the magic_flags received from the splitter?

**Comment by jellysheep** [comment]
Hi Vicente, yes, exactly. Some basic peer class will have to do the initial TCP communication with the splitter in the first place, and the specialized PeerDBS etc. peer classes have to take over as soon as the magic_flags are known.

**Comment by jellysheep** [comment]
Hi Vicente, yes, exactly. Some basic peer class will have to do the initial TCP communication with the splitter in the first place, and the specialized PeerDBS etc. peer classes have to take over as soon as the magic_flags are known.

**Comment by vicente-gonzalez-ruiz** [comment]
Hi. I think that this issue can be closed because we decided to compile statically the number of sets of rules used.
