### ISSUE TITLE
Unable to Find Slideshow

### ISSUE THREAD

**Issue by nkyadav4598** [P2PSP/core#136]
The slideshow containing Information about NAT traversal in the P2PSP protocol is not linked properly in the markdown file:-
https://github.com/P2PSP/core/blob/master/doc/NTS/NAT_traversal.md 

<img width="457" alt="URL NOT FOUND" src="https://user-images.githubusercontent.com/18068869/37879899-9863edc2-309d-11e8-86af-0c69a523d02b.png">

**Comment by cristobalmedinalopez** [comment]
Hi,
That slideshow is not available. We will try to put it online as soon as possible.
Thanks!

**Comment by vicente-gonzalez-ruiz** [comment]
Solved.

**Comment by vicente-gonzalez-ruiz** [comment]
Solved.
