### ISSUE TITLE
Chromecast integration

### ISSUE THREAD

**Issue by josejuansanchez** [P2PSP/core#18]
Reference: 
- [pychromecast](https://github.com/balloob/pychromecast)
  Library for Python 2 and 3 to communicate with the Google Chromecast. It currently supports:
  - Auto discovering connected Chromecasts on the network
  - Start the default media receiver and play any online media
  - Control playback of current playing media
  - Implement Google Chromecast api v2
  - Communicate with apps via channels
  - Easily extendable to add support for unsupported namespaces

**Comment by vicente-gonzalez-ruiz** [comment]
The GUI stuff should be discussed in a different repository.
