### ISSUE TITLE
Timeline with the number of peers entering and leaving the team (Audience charts)

### ISSUE THREAD

**Issue by josejuansanchez** [P2PSP/core#19]

**Comment by maniotrix** [comment]
So what are the parameters we have for this purpose?
* time when peers enter in the team
* time when they leave the team
* total time they have spent on a particular channel in the team

These are few parameters I have in my mind currently.

Any other suggestions?

**Comment by vicente-gonzalez-ruiz** [comment]
The GUI stuff should be discussed in a different repository.
