### ISSUE TITLE
A diagram with the final architecture would be great to view all the dependencies between classes.

### ISSUE THREAD

**Issue by josejuansanchez** [P2PSP/core#23]

**Comment by maniotrix** [comment]
![gui_architecture](https://cloud.githubusercontent.com/assets/7295721/8106008/80692bfc-105b-11e5-8d72-18fe05a7ccab.png)

**Comment by josejuansanchez** [comment]
Could be possible to have three columns (view, controller and model) and reorganize all the elements in the columns, in order to know which classes are acting as view, controller or model?

Also, could be great to design the diagram using a tool that allow us to modify the diagram easily.

**Comment by cristobalmedinalopez** [comment]
And a white background too ;-)

**Comment by vicente-gonzalez-ruiz** [comment]
The GUI stuff should be discussed in a different repository.
