### ISSUE TITLE
App state management

### ISSUE THREAD

**Issue by maniotrix** [P2PSP/core#57]
Currently App is not restored to its previous state when its restarted.

**Comment by maniotrix** [comment]
Things to be restored when app restarts:
Channels in the icon view.
A list of recent channels played in the 'Recent Channels" submenu in the "File" Menu.
Audience Charts.
Widgets which have been hidden by user.
Volume of the player.
Path to the last exported file.


Any other suggestions.

**Comment by josejuansanchez** [comment]
Your proposal sounds good to me.

**Comment by sumanswaroop** [comment]
is this still open?

**Comment by vicente-gonzalez-ruiz** [comment]
Hi, yes sumanswaroop, I think so.

**Comment by vicente-gonzalez-ruiz** [comment]
The GUI stuff should be discussed in a different repository.
