### ISSUE TITLE
Sometimes the video is not displayed after select a channel and press play button.

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/core#59]

**Comment by jinankjain** [comment]
Is this bug still open, then I would like to work on this bug

**Comment by maniotrix** [comment]
Yes this bug is open.

**Comment by jinankjain** [comment]
I have successfully build the system.
@maniotrix Could you please how to reproduce the bug i.e what should I follow to see the error

**Comment by jinankjain** [comment]
@maniotrix  One more thing I was trying everything locally following the steps given on http://p2psp.org/en/download but nothing was running could you please help me out in that?

**Comment by cristobalmedinalopez** [comment]
Hi @jinankjain,

Please, try it following the instructions at https://github.com/P2PSP/p2psp/tree/master/doc/advanced-user-manual or https://github.com/P2PSP/p2psp/tree/master/doc/user-manual

Thanks!

**Comment by vicente-gonzalez-ruiz** [comment]
The GUI stuff should be discussed in a different repository.
