### ISSUE TITLE
Download a channel thumbnail from a remote location

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/core#92]
In the GUI (gui brach: https://github.com/P2PSP/p2psp/tree/gui) would be interesting to download a thumbnail of the channel from a URL and save it into a local location. Also, the use of the relative path instead of absolute path would be great.

**Comment by iharsh234** [comment]
`ffmpeg -i http://upload.wikimedia.org/wikipedia/commons/7/79/Big_Buck_Bunny_small.ogv -r 0.1315097317201473 -s 480x270 -an -f image2 thumb_%d.jpg`
This command generates some thumbnails of given URL using ffmpeg multimedia framework.
We could do this at real time as well  and at same time when we transcoding video from URL.

**Comment by cristobalmedinalopez** [comment]
Hi @iharsh234,

Thanks! It sounds very interesting (we could do it!) but I meant to something much more simple. In the GUI, when you add a channel, you can enter a URL for the channel thumbnail, the problem is that in this moment it only works with local images.

**Comment by vicente-gonzalez-ruiz** [comment]
The GUI stuff should be discussed in a different repository.
